// THIS FILE WAS GENERATED BY MSGMAP. DON'T TOUCH IT!
//
// Instead, edit its corresponding .yml files and run this
// project's msgmap script to generate new headers.

#ifndef _MSGMAP_about_dialog_TRANSLATIONS_H
#define _MSGMAP_about_dialog_TRANSLATIONS_H

#include "msgmap.h"

#include <wchar.h>

#ifndef _MSC_VER
    #error "msgmap: Wide character strings are only supported in MSVC"
#endif

typedef struct _mm_about_dialog_translations_t
{
    const wchar_t *app_info;
    const wchar_t *github_link;
    const wchar_t *ok_button;
    wchar_t *(*app_version)(unsigned int major, unsigned int minor, unsigned int revision);
} mm_about_dialog_translations_t;

MM_DEC const mm_about_dialog_translations_t *mm_get_about_dialog_translations(void);

#ifdef MSGMAP_IMPL

// en_US strings

static wchar_t *mm_about_dialog_translations_app_version_en_US(unsigned int major, unsigned int minor, unsigned int revision)
{
    MM_FORMATTED_STRING_BODY_W(L"Version %u.%u.%u", major, minor, revision)
}

static const mm_about_dialog_translations_t mm_about_dialog_translations_en_US = {
    L"NTMU is a system file modification tool for Windows. It is free and open-source software, licensed under the GNU General Public License (GPL) 3.0.", // app_info
    L"GitHub repository", // github_link
    L"OK", // ok_button
    mm_about_dialog_translations_app_version_en_US,
};

static const mm_translation_mapping_t mm_about_dialog_map[] = {
    { (void *)&mm_about_dialog_translations_en_US, "en", "US" },
};

MM_IMPL const mm_about_dialog_translations_t *mm_get_about_dialog_translations(void)
{
    return (const mm_about_dialog_translations_t *)mm_get_translations(mm_about_dialog_map, 1);
}

#endif // MSGMAP_IMPL

#endif // _MSGMAP_about_dialog_TRANSLATIONS_H