// THIS FILE WAS GENERATED BY MSGMAP. DON'T TOUCH IT!
//
// Instead, edit its corresponding .yml files and run this
// project's msgmap script to generate new headers.

#ifndef _MSGMAP_app_TRANSLATIONS_H
#define _MSGMAP_app_TRANSLATIONS_H

#include "msgmap.h"

#include <wchar.h>

#ifndef _MSC_VER
    #error "msgmap: Wide character strings are only supported in MSVC"
#endif

typedef struct _mm_app_translations_t
{
    const wchar_t *app_name;
    const wchar_t *privilege_escalation_failed;
    const wchar_t *temp_dir_creation_failed;
    const wchar_t *bad_pack_arg;
    wchar_t *(*bad_argument)(const wchar_t *arg);
} mm_app_translations_t;

MM_DEC const mm_app_translations_t *mm_get_app_translations(void);

#ifdef MSGMAP_IMPL

// en_US strings

static wchar_t *mm_app_translations_bad_argument_en_US(const wchar_t *arg)
{
    MM_FORMATTED_STRING_BODY_W(L"Invalid argument '%s'.", arg)
}

static const mm_app_translations_t mm_app_translations_en_US = {
    L"Windows NT Modding Utility", // app_name
    L"Failed to acquire the necessary privileges.", // privilege_escalation_failed
    L"Failed to create the temporary directory.", // temp_dir_creation_failed
    L"Not enough arguments for pack.", // bad_pack_arg
    mm_app_translations_bad_argument_en_US,
};

static const mm_translation_mapping_t mm_app_map[] = {
    { (void *)&mm_app_translations_en_US, "en", "US" },
};

MM_IMPL const mm_app_translations_t *mm_get_app_translations(void)
{
    return (const mm_app_translations_t *)mm_get_translations(mm_app_map, 1);
}

#endif // MSGMAP_IMPL

#endif // _MSGMAP_app_TRANSLATIONS_H