// THIS FILE WAS GENERATED BY MSGMAP. DON'T TOUCH IT!
//
// Instead, edit its corresponding .yml files and run this
// project's msgmap script to generate new headers.

#ifndef _MSGMAP_ini_errors_TRANSLATIONS_H
#define _MSGMAP_ini_errors_TRANSLATIONS_H

#include "msgmap.h"

#include <wchar.h>

#ifndef _MSC_VER
    #error "msgmap: Wide character strings are only supported in MSVC"
#endif

typedef struct _mm_ini_errors_translations_t
{
    wchar_t *(*open_failed)(const wchar_t *file);
    wchar_t *(*unclosed_section_header)(int line);
    wchar_t *(*value_outside_section)(int line);
    wchar_t *(*missing_equals)(int line);
} mm_ini_errors_translations_t;

MM_DEC const mm_ini_errors_translations_t *mm_get_ini_errors_translations(void);

#ifdef MSGMAP_IMPL

// en_US strings

static wchar_t *mm_ini_errors_translations_open_failed_en_US(const wchar_t *file)
{
    MM_FORMATTED_STRING_BODY_W(L"Failed to open file '%s' for reading.", file)
}

static wchar_t *mm_ini_errors_translations_unclosed_section_header_en_US(int line)
{
    MM_FORMATTED_STRING_BODY_W(L"Unclosed section header on line %d.", line)
}

static wchar_t *mm_ini_errors_translations_value_outside_section_en_US(int line)
{
    MM_FORMATTED_STRING_BODY_W(L"Value outside of section on line %d.", line)
}

static wchar_t *mm_ini_errors_translations_missing_equals_en_US(int line)
{
    MM_FORMATTED_STRING_BODY_W(L"Missing '=' on line %d.", line)
}

static const mm_ini_errors_translations_t mm_ini_errors_translations_en_US = {
    mm_ini_errors_translations_open_failed_en_US,
    mm_ini_errors_translations_unclosed_section_header_en_US,
    mm_ini_errors_translations_value_outside_section_en_US,
    mm_ini_errors_translations_missing_equals_en_US,
};

static const mm_translation_mapping_t mm_ini_errors_map[] = {
    { (void *)&mm_ini_errors_translations_en_US, "en", "US" },
};

MM_IMPL const mm_ini_errors_translations_t *mm_get_ini_errors_translations(void)
{
    return (const mm_ini_errors_translations_t *)mm_get_translations(mm_ini_errors_map, 1);
}

#endif // MSGMAP_IMPL

#endif // _MSGMAP_ini_errors_TRANSLATIONS_H