// THIS FILE WAS GENERATED BY MSGMAP. DON'T TOUCH IT!
//
// Instead, edit its corresponding .yml files and run this
// project's msgmap script to generate new headers.

#ifndef _MSGMAP_main_window_TRANSLATIONS_H
#define _MSGMAP_main_window_TRANSLATIONS_H

#include "msgmap.h"

#include <wchar.h>

#ifndef _MSC_VER
    #error "msgmap: Wide character strings are only supported in MSVC"
#endif

typedef struct _mm_main_window_translations_t
{
    const wchar_t *menu_file;
    const wchar_t *menu_file_open;
    const wchar_t *menu_file_unload;
    const wchar_t *menu_file_exit;
    const wchar_t *menu_tools;
    const wchar_t *menu_tools_restart_explorer;
    const wchar_t *menu_tools_clear_icon_cache;
    const wchar_t *menu_tools_system_restore;
    const wchar_t *menu_help;
    const wchar_t *menu_help_topics;
    const wchar_t *menu_help_get_packs;
    const wchar_t *menu_help_about;
    const wchar_t *pack_name;
    const wchar_t *pack_author;
    const wchar_t *pack_version;
    const wchar_t *apply_button;
    const wchar_t *no_preview;
    const wchar_t *no_readme;
    const wchar_t *no_options;
    const wchar_t *no_pack_loaded;
    const wchar_t *not_specified;
    const wchar_t *pack_file_filter;
    const wchar_t *pack_apply_warning;
    const wchar_t *pack_apply_successful;
    const wchar_t *pack_apply_failed;
} mm_main_window_translations_t;

MM_DEC const mm_main_window_translations_t *mm_get_main_window_translations(void);

#ifdef MSGMAP_IMPL

// en_US strings

static const mm_main_window_translations_t mm_main_window_translations_en_US = {
    L"&File", // menu_file
    L"&Open Pack...\tCtrl+O", // menu_file_open
    L"&Unload Pack...\tCtrl+W", // menu_file_unload
    L"E&xit\tAlt+F4", // menu_file_exit
    L"&Tools", // menu_tools
    L"&Restart Explorer", // menu_tools_restart_explorer
    L"&Clear Icon/Thumbnail Cache", // menu_tools_clear_icon_cache
    L"Manage &System Restore...", // menu_tools_system_restore
    L"&Help", // menu_help
    L"&Help Topics...", // menu_help_topics
    L"&Get Packs...", // menu_help_get_packs
    L"&About Windows NT Modding Utility...", // menu_help_about
    L"Name:", // pack_name
    L"Author:", // pack_author
    L"Version:", // pack_version
    L"&Apply", // apply_button
    L"No preview", // no_preview
    L"This pack does not have a README", // no_readme
    L"This pack does not have any options", // no_options
    L"No pack loaded", // no_pack_loaded
    L"(Not specified)", // not_specified
    L"INI Files (*.ini)#*.ini#All Files (*.*)#*.*##", // pack_file_filter
    L"Applying a pack can make changes to system files and registry entries. If the pack you have selected does so, it is recommended that you:\n\n- Create a restore point (Tools -> Manage System Restore...)\n- Disable Windows Update (can be done through external tools)\n\nDo you wish to proceed?", // pack_apply_warning
    L"The pack was applied successfully.", // pack_apply_successful
    L"Failed to apply the selected pack. See the log for more details.", // pack_apply_failed
};

static const mm_translation_mapping_t mm_main_window_map[] = {
    { (void *)&mm_main_window_translations_en_US, "en", "US" },
};

MM_IMPL const mm_main_window_translations_t *mm_get_main_window_translations(void)
{
    return (const mm_main_window_translations_t *)mm_get_translations(mm_main_window_map, 1);
}

#endif // MSGMAP_IMPL

#endif // _MSGMAP_main_window_TRANSLATIONS_H