// THIS FILE WAS GENERATED BY MSGMAP. DON'T TOUCH IT!
//
// Instead, edit its corresponding .yml files and run this
// project's msgmap script to generate new headers.

#ifndef _MSGMAP_unattend_window_TRANSLATIONS_H
#define _MSGMAP_unattend_window_TRANSLATIONS_H

#include "msgmap.h"

#include <wchar.h>

#ifndef _MSC_VER
    #error "msgmap: Wide character strings are only supported in MSVC"
#endif

typedef struct _mm_unattend_window_translations_t
{
    const wchar_t *loading_pack;
    const wchar_t *pack_load_failed;
    const wchar_t *close_button;
    wchar_t *(*applying_pack)(const wchar_t *pack_name);
    wchar_t *(*pack_apply_failed)(const wchar_t *pack_name);
    wchar_t *(*pack_apply_failed_message)(const wchar_t *pack_name);
} mm_unattend_window_translations_t;

MM_DEC const mm_unattend_window_translations_t *mm_get_unattend_window_translations(void);

#ifdef MSGMAP_IMPL

// en_US strings

static wchar_t *mm_unattend_window_translations_applying_pack_en_US(const wchar_t *pack_name)
{
    MM_FORMATTED_STRING_BODY_W(L"Applying pack \"%s\"...", pack_name)
}

static wchar_t *mm_unattend_window_translations_pack_apply_failed_en_US(const wchar_t *pack_name)
{
    MM_FORMATTED_STRING_BODY_W(L"Failed to apply pack \"%s\".", pack_name)
}

static wchar_t *mm_unattend_window_translations_pack_apply_failed_message_en_US(const wchar_t *pack_name)
{
    MM_FORMATTED_STRING_BODY_W(L"Failed to apply pack \"%s\". See the log for details.", pack_name)
}

static const mm_unattend_window_translations_t mm_unattend_window_translations_en_US = {
    L"Loading pack...", // loading_pack
    L"Failed to load pack.", // pack_load_failed
    L"&Close", // close_button
    mm_unattend_window_translations_applying_pack_en_US,
    mm_unattend_window_translations_pack_apply_failed_en_US,
    mm_unattend_window_translations_pack_apply_failed_message_en_US,
};

static const mm_translation_mapping_t mm_unattend_window_map[] = {
    { (void *)&mm_unattend_window_translations_en_US, "en", "US" },
};

MM_IMPL const mm_unattend_window_translations_t *mm_get_unattend_window_translations(void)
{
    return (const mm_unattend_window_translations_t *)mm_get_translations(mm_unattend_window_map, 1);
}

#endif // MSGMAP_IMPL

#endif // _MSGMAP_unattend_window_TRANSLATIONS_H